# Generated by Django 5.0.4 on 2024-04-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('pettype', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='hform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('pettype', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('time', models.TimeField()),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
