# Generated by Django 5.0.4 on 2024-04-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('pet', models.CharField(max_length=50)),
                ('type1', models.CharField(max_length=50)),
            ],
        ),
    ]
