# Generated by Django 5.0.4 on 2024-04-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming', '0002_bgroomer_hgroomer_kgroomer_lgroomer_mgroomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kgroomer',
            name='image',
            field=models.URLField(),
        ),
    ]
