from django.db import models
class ddoctor(models.Model):
    image=models.ImageField()
    name=models.CharField(max_length=50)
    shortaddress=models.CharField(max_length=500)
    address=models.TextField()
    phone_no=models.CharField(max_length=50)
    opening_Hours=models.CharField(max_length=50)
    rating=models.CharField(max_length=50)

class ldoctor(models.Model):
    image=models.ImageField()
    name=models.CharField(max_length=50)
    shortaddress=models.CharField(max_length=500)
    address=models.TextField()
    phone_no=models.CharField(max_length=50)
    opening_Hours=models.CharField(max_length=50)
    rating=models.CharField(max_length=50)
class mdoctor(models.Model):
    image=models.ImageField()
    name=models.CharField(max_length=50)
    shortaddress=models.CharField(max_length=500)
    address=models.TextField()
    phone_no=models.CharField(max_length=50)
    opening_Hours=models.CharField(max_length=50)
    rating=models.CharField(max_length=50)
class bdoctor(models.Model):
    image=models.ImageField()
    name=models.CharField(max_length=50)
    shortaddress=models.CharField(max_length=500)
    address=models.TextField()
    phone_no=models.CharField(max_length=50)
    opening_Hours=models.CharField(max_length=50)
    rating=models.CharField(max_length=50)
class kdoctor(models.Model):
    image=models.ImageField()
    name=models.CharField(max_length=50)
    shortaddress=models.CharField(max_length=500)
    address=models.TextField()
    phone_no=models.CharField(max_length=50)
    opening_Hours=models.CharField(max_length=50)
    rating=models.CharField(max_length=50)
class hdoctor(models.Model):
    image=models.ImageField()
    name=models.CharField(max_length=50)
    shortaddress=models.CharField(max_length=500)
    address=models.TextField()
    phone_no=models.CharField(max_length=50)
    opening_Hours=models.CharField(max_length=50)
    rating=models.CharField(max_length=50)
# claeate your models here.
