# Generated by Django 5.0.4 on 2024-04-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kadopt',
            name='image',
            field=models.URLField(verbose_name='https://images.jdmagicbox.com/comp/kolkata/r8/033pxx33.xx33.200731182510.n6r8/catalogue/animal-lovers-pet-shop-behala-kolkata-pet-accessory-dealers-d7eo4owy6q-250.jpg?clr='),
        ),
    ]
