# Generated by Django 5.0.4 on 2024-04-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_alter_kadopt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kadopt',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
